### PR TITLE
chore: bump handlersjs and use its exported http sequence handler

### PR DESCRIPTION
**Pull request by arnevandoorslaer**

### CODE REVIEW

**Review by BelgianNoise — APPROVED** [review]
Building, testing, starting and all that works.
@AbelVandenBriel @JasperVandenberghen  , it might be usefull if you could tell me/us how we can test PRs better. Like what kind of requests should we try ?

**Comment by JasperVandenberghen** [comment]
> Building, testing, starting and all that works. @AbelVandenBriel @JasperVandenberghen , it might be useful if you could tell me/us how we can test PRs better. Like what kind of requests should we try ?

Best thing besides running the tests is going through the demo flow actually. Especially the auth0 one. Ofcourse you might have changed something those configs did not use but we might notice in the changes.

**Comment by AbelVandenBriel** [comment]
Agree with Jasper, going through the demo flows is probably the best thing. It gives an idea wether the overall flow still works. In this PR that would be a good test :)

**Review by JasperVandenberghen — APPROVED** [review]
Flow works as intended but is it just me or does the CSS not load on the panva and keycloak demo? @AbelVandenBriel how is that for you?

**Review by JasperVandenberghen — APPROVED** [review]

**Review by AbelVandenBriel — APPROVED** [review]

**Pull request merged**
