### PR TITLE
chore: bump handlersjs

### PR DESCRIPTION
**Pull request by BelgianNoise**

### CODE REVIEW

**Comment by BelgianNoise** [comment]
@AbelVandenBriel as discussed earlier on Tandem I tried to bump handlersjs in the `dgt-id-proxy` package. 2 out of 3 demo's alraedy crashed on develop at startup. 🤔 

### On origin/develop
- 🔴  `npm run demo:auth0`
- ✅  `npm run demo:panva`
- 🔴 `npm run demo:keycloak`

### On chore/bump-handlersjs (this branch)
- 🔴 `npm run demo:auth0` 
- ✅  `npm run demo:panva`
- 🔴 `npm run demo:keycloak`

Maybe you or @JasperVandenberghen know what's wrong with the demo's on develop ? Not sure how to proceed.

**Comment by BelgianNoise** [comment]
Wow, I just noticed @arnevandoorslaer had an open PR bumping handlersjs ( https://github.com/digita-ai/dgt-id-broker/pull/385 ) bumping handlersjs to 0.10.0.

**Comment by JasperVandenberghen** [comment]
Yes, was just about to comment that. And I believe he fixed all the demo's there.

**Comment by BelgianNoise** [comment]
> Yes, was just about to comment that. And I believe he fixed all the demo's there.

Yep idd, I just read through the code.

@AbelVandenBriel , Im closing this PR.

**Pull request closed without merging**
